#include <stdio.h>
void output_compile_time_options(void)
{
printf(
"        cosa#!/bin/bash\n"
"        PERIODIC\n"
"        UNEQUALSOFTENINGS\n"
"        PMGRID=270\n"
"        PLACEHIGHRESREGION=2\n"
"        ENLARGEREGION=1.5\n"
"        MULTIPLEDOMAINS=4\n"
"        PEANOHILBERT\n"
"        WALLCLOCK\n"
"        MYSORT\n"
"        DOUBLEPRECISION\n"
"        DOUBLEPRECISION_FFTW\n"
"        tree_sage_run\n"
"        THIS_IS_A_COSANG_RUN\n"
"        Extrap\n"
"        Mass_Adjust\n"
"        Disk_Orientation\n"
"        zoomsim\n"
"        OVERRIDE_STOP_FOR_SUBOPTIMUM_DOMAINS\n"
"        FOF\n"
"        FOF_PRIMARY_LINK_TYPES=2\n"
"        FOF_SECONDARY_LINK_TYPES=1+16+32\n"
"        FOF_GROUP_MIN_LEN=32\n"
"        SUBFIND\n"
"        MAX_NGB_CHECK=2\n"
"        SUBFIND_SAVE_PARTICLELISTS\n"
"        ORDER_SNAPSHOTS_BY_ID\n"
"        LINKLENGTH=0.16\n"
"        NO_GAS_CLOUDS\n"
"        NOTEST_FOR_IDUNIQUENESS\n"
"        NO_ISEND_IRECV_IN_DOMAIN\n"
"        FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG\n"
"        OUTPUTACCELERATION\n"
"        OUTPUTTIMESTEP\n"
"        HAVE_HDF5\n"
"\n");
}
